### ISSUE TITLE
[Request] Add compiled binaries for all new releases

### ISSUE THREAD

**Issue by whalehub** [FiloSottile/age#133]
I want to use a script to update `age` from time to time, but for it to work, new releases need to have compiled binaries attached to them. As of right now, only the release v1.0.0-beta2 fulfills this criteria while the releases v1.0.0-beta3 and v1.0.0-beta4 don't.

This issue is tangentially related to #25 which would automate this process for you.

**Comment by skorokithakis** [comment]
I would like to second this, I am considering using `age` but not having binaries doesn't look good...

**Comment by parkr** [comment]
In addition to binaries (which I would also like!), I'd like checksums of the binaries to ensure the integrity of the binaries I download. Thanks, @FiloSottile!

**Comment by CHTJonas** [comment]
Dup'ed by #164

**Comment by Fastidious** [comment]
@CHTJonas how does this helps? This issue is older than the one you mention.

**Comment by CHTJonas** [comment]
@Fastidious, sorry if I was unclear - what I mean is that this issue is duplicated by the one referenced above. There's actually three unique tickets which all reference the lack of binaries and which all contain unduplicated discussion. I've linked them all using the comments section so that they're all easily viewable by someone if/when they get around to taking a look at this.

**Comment by parkr** [comment]
Thank you!
