### ISSUE TITLE
spec: Cannot access spec URL

### ISSUE THREAD

**Issue by jtrauntvein** [FiloSottile/age#156]
I have been trying since Saturday to read the age spec URL but, each time, Chrome reports an invalid TLS negotiation and refuses to load the site.

**Comment by FiloSottile** [comment]
I can load https://age-encryption.org/v1 with no issues from Chrome. Can you provide a screenshot of the error and of the certificate?

**Comment by jtrauntvein** [comment]
It appears to be a root trust issue From: Filippo Valsorda <notifications@github.com>Date: Tuesday, November 24, 2020 at 09:09To: FiloSottile/age <age@noreply.github.com>Cc: jtrauntvein <jtrauntvein@gmail.com>, Author <author@noreply.github.com>Subject: Re: [FiloSottile/age] spec: Cannot access spec URL (#156)I can load https://age-encryption.org/v1 with no issues from Chrome. Can you provide a screenshot of the error and of the certificate?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by FiloSottile** [comment]
The certificate is a simple Let's Encrypt one, so the issue must be on your side.

Some misguided "security" products cause TLS errors when they attempt to block a website, and age-encryption.org ended up on some blocklists in the past because age was used in some malware (even if of course that malware did not connect to age-encryption.org at all).

If you could figure out what vendor is doing this and report it to them, I'd be grateful.

**Comment by magical** [comment]
@jtrauntvein Here's a direct link to the google doc https://docs.google.com/document/d/11yHom20CrsuX8KQJXBBw04s80Unjv8zCg_A7sPAX_9Y/preview (age-encryption.org/v1 simply redirects here)
