### ISSUE TITLE
Couldn't decrypt with that SSH key, please choose another one.

### ISSUE THREAD

**Issue by KittyFu307** [FiloSottile/age#545]
## Environment

* OS: mac 
* age version: 12.2.1 (21D62)

## What happened
./proof-sh/proof.sh  

```
<insert terminal transcript here>

Will use SSH key to generate proof data. Press enter to proceed. 

Couldn't decrypt with that SSH key, please choose another one.
Possible cause is: 
age: error: no identity matched any of the recipients
age: report unexpected or unhelpful errors at https://filippo.io/age/report
```

**Comment by cipriancraciun** [comment]
Please note that the problem you are describing doesn't pertain directly to `age` (the repository you've submitted this issue to), but instead it is a problem pertaining to the project / tool that happens to be using `age` as a dependency behind the scenes.

Based on other similar issues like yours that were received in the previous days, most likely your problem is with the `fluencelabs/dev-rewards` project as described here: <https://github.com/fluencelabs/dev-rewards/issues/19>

If so, please kindly close this issue here, and open a new ticket to the proper project.
