### ISSUE TITLE
unable to decrypt a proof with ssh key

### ISSUE THREAD

**Issue by viraj124** [FiloSottile/age#573]
## Environment

* OS: mac os
* age version: v1.1.1

## What were you trying to do
Hi,
I am trying to decrypt a proof with my ssh private key which I regenerated
## What happened
but even with the right ssh key path I am getting this error
`age: error: no identity matched any of the recipients`

How can I fix this ?

**Comment by cipriancraciun** [comment]
Based on other similar issues like yours that were received in the previous days, most likely your problem is with the `fluencelabs/dev-rewards` project as described here: <https://github.com/fluencelabs/dev-rewards/issues/19>

If so, please kindly close this issue here, and open a new ticket to the proper project.
