### ISSUE TITLE
Empty password

### ISSUE THREAD

**Issue by proyb6** [FiloSottile/age#62]
UX appear to be complex for non-technical user, could return `Sorry, you have enter incorrect passphrase` regardless of empty or wrong passphrase.

```
 age -d README.md.age 
Enter passphrase: 
Error: empty scrypt password
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
```

**Comment by FiloSottile** [comment]
Hmm, isn't it more useful to know what the problem is specifically?

How about "Error: passphrase can't be empty."?

**Comment by alerque** [comment]
Especially since the terminal won't echo the input, knowing that the error was "empty password" not "wrong password" is _very_ useful information. If you want to simplify for non-technical users dropping the mention of "scrypt" might be okay, but the error message should be as specific as possible without leaking security info.
