### ISSUE TITLE
RFE: Allow use of ssh public key *path* rather than key contents for recipient

### ISSUE THREAD

**Issue by larsks** [FiloSottile/age#84]
## Environment

* OS: fedora 30
* age version: e43cf8b4a2d571df8dcb30783a460acbf188adb4

## What were you trying to do

I wish that I could encrypt to a public key by specifying a path to the public key file:

    age -r ~/keys/someperson.pub

Rather than the *contents * of the public key file:

    age -r $(cat ~/keys/someperson.pub)

(Maybe this would require a new option (`-R`?) rather than overloading the behavior of the existing `--recipient/-r` option)

And obviously it would be nice if this same feature were available for `age` public keys as well.

**Comment by cyb3rz3us** [comment]
If possible, I would vote for using the same '-r' but if not feasible, then whatever works to get this implemented.

**Comment by nxg** [comment]
(This comment may be redundant, given the presence of the linked pull request; if so, just ignore)

Another possibility is to distinguish a key-file from a key by prefixing it with `@`

    age -r @~/keys/someperson.pub

(`curl --data-binary` has a syntax like this, if it's useful to quote a precedent).

Another possibility is to regard the `-r` option value as referring to a file if there's a file by that name, and as an explicit key otherwise.  It's true that adds a heuristic element, but it's only likely to get the wrong answer if there is (deliberately,  mischievously, or accidentally) a file which shares its name with a key-value.

Adding `file://` URLs is cute, and very general, but not _massively_ easier to script (which is the real problem with the key-only value for `-r`).  Excess generality can be a vice, as well, especially if it requires that other libraries be pulled in.

Overall, adding `-R` seems simpler.
